import '../../app/globals.css'

import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import { ToggleMenuProvider } from '@/contexts/toggle-menu-mobile'

const firaCode = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={firaCode.className}>
        <div className="flex min-h-screen flex-col">
          <ToggleMenuProvider>
            <Header />
            <main className="flex flex-1 flex-col bg-primary-mid-blue pt-14">
              {children}
            </main>
            <Footer />
          </ToggleMenuProvider>
        </div>
      </body>
    </html>
  )
}
